server:
  port: 8080

spring:
  http:
    encoding:
      charset: "UTF-8"
  jackson:
    time-zone: "America/Lima"
    date-format: "yyyy-MM-dd"
    timestamp-format: "yyyy-MM-dd HH:mm:ss"
  data:
    mongodb:
      uri: "mongodb+srv://jhosef:quijana@cluster0.zxagh.mongodb.net/web?retryWrites=true&w=majority"