name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and push Docker image
        run: |
          echo ${{ secrets.GCP_KEY_FILE }} | base64 -d > key.json
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/spring-boot-app:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/spring-boot-app:${{ github.sha }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: key.json

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy spring-boot-app \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/spring-boot-app:${{ github.sha }} \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
        env:
          GOOGLE_APPLICATION_CREDENTIALS: key.json
        working-directory: ./path/to/your/spring-boot-app