name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_ID }}/api-products:latest .
      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_ID }}/api-products:latest
      - name: Deploy
        run: |
          gcloud run deploy api-products \
          --region us-east1 \
          --image gcr.io/${{ secrets.GCP_ID }}/api-products \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_ID }}